### ISSUE TITLE
Wrong JavaSignature attributes in FingerprintManager

### ISSUE THREAD

**Issue by rlebeau** [FMXExpress/android-object-pascal-wrapper#1]
In `/android-23/android.hardware.fingerprint.FingerprintManager.pas`, the `JFingerprintManager` interface has the wrong `JavaSignature` applied to it:

```
[JavaSignature('android/hardware/fingerprint/FingerprintManager$AuthenticationCallback')]
JFingerprintManager = interface(JObject)
  ...
end;
```

This causes "invoke error: method not found" errors when calling `JFingerprintManager` methods at runtime:

```
var
  JavaObject : JObject;
  FingerprintManager : JFingerprintManager;
begin
  JavaObject:=TAndroidHelper.Context.getSystemService(TJContext.JavaClass.FINGERPRINT_SERVICE);
  FingerprintManager:=TJFingerprintManager.Wrap((JavaObject as ILocalObject).GetObjectID);
  if FingerprintManager.isHardwareDetected then // <-- error here!
  begin
    ...
  end;
end;
```

The `$AuthenticationCallback` does not belong in the `JavaSignature` statement.

Likewise, in `/android-23/android.hardware.fingerprint.FingerprintManager_AuthenticationCallback.pas`, the `JFingerprintManager_AuthenticationCallback` interface has a wrong `JavaSignature`, too:

```
[JavaSignature('android/hardware/fingerprint/FingerprintManager_AuthenticationCallback')] 
JFingerprintManager_AuthenticationCallback = interface(JObject)
  ...
end;
```

Should be:

```
[JavaSignature('android/hardware/fingerprint/FingerprintManager$AuthenticationCallback')] 
JFingerprintManager_AuthenticationCallback = interface(JObject)
  ...
end;
```

Likewise, in `/android-23/android.hardware.fingerprint.FingerprintManager_AuthenticationResult.pas`:

```
[JavaSignature('android/hardware/fingerprint/FingerprintManager_AuthenticationResult')] 
JFingerprintManager_AuthenticationResult = interface(JObject) 
  ...
end; 
```

Should be:

```
[JavaSignature('android/hardware/fingerprint/FingerprintManager$AuthenticationCallback')] 
JFingerprintManager_AuthenticationCallback = interface(JObject)
  ...
end;
```

**Comment by FMXExpress** [comment]
I'll look at it. It's possible I didn't do the most recent conversion correctly because it's a two step process to merge all of the circular references. I use Java2pas.
